coverage:
  status:
    project:
      default:
        target: 60% # Set the default target to 60%
        threshold: 40% # Set the threshold for the "yellow" range to 40%
        base: auto
        paths:
          - "src/main/java"
  range: "40...60" # Set the range to "40...60" for the "yellow" range
  round: down
  precision: 2