store:
  default: [] # remove square brackets if setting default store(s) per world
#    'null': minecraft:the_end
#    world: minecraft:overworld
  max-owned-stores: 1
  min-dimensions:
    x: 3
    y: 3
    z: 3
  max-dimensions:
    x: 16
    y: 8
    z: 16
  min-volume: 27
  max-volume: 1024
  off-limits:
  - world(minecraft:overworld),start(-20,-64,-20),end(20,320,20)
  - world(minecraft:the_nether),start(-20,-64,-20),end(20,128,20)
  - world(minecraft:the_end),start(-20,-64,-20),end(20,256,20)
messages: [] # remove square brackets if using custom messages
#  NO_PERMS_CMD: §cDon't even try it! §fYou don't have permission to do that.
#  NOT_BUYING: §cThe store is not buying §6{material}§c at this time!