name: @project.name@
version: @project.version@
author: MrSparkzz (Brendon Butler)
main: net.sparkzz.shops.Shops
api-version: 1.18

depend: [ Vault ]
website: shops.sparkzz.net
commands:
  shop:
    description: Interact with current shop
    usage: /<command> [buy|sell] <item> <quantity>
    permission: shops.command.interact
  shops:
    description: Shops plugin info
    usage: /<command>
    permission: shops.command.shops
#commands:
  #<command>:
    #description: appears in /help
    #usage: command [one|two] <player_name>
