name: Shops
version: 0.0.1-PRERELEASE
author: MrSparkzz
main: net.sparkzz.shops.Shops
api-version: 1.18

#depend: PluginName
website: shops.sparkzz.net
commands:
  shops:
    description: Shops command for plugin info
    usage: /<command>
    permission: shops.command.shops
#commands:
  #<command>:
    #description: appears in /help
    #usage: command [one|two] <player_name>
