name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build and run unit tests
        run: mvn clean install

      - name: Generate code coverage report
        run: mvn jacoco:report

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Extract coverage percentage
        id: extract-coverage
        run: echo "::set-output name=coverage::${{ steps.codecov.outputs.coverage }}"

      - name: Run integration tests
        run: mvn verify

      - name: Check documentation and publish reports
        run: mvn validate site