name: CI Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
  workflow_call:
    inputs:
      create_release_artifacts:
        description: 'Create shaded JARs for release'
        required: false
        type: boolean
        default: false

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'

      - name: Build and run unit tests
        run: mvn clean install

      - name: Build shaded JARs
        if: ${{ inputs.create_release_artifacts }}
        run: mvn package -DskipTests

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/target/*.jar
            !**/target/original-*.jar
          retention-days: 1

      - name: Send Discord build notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: ${{ job.status == 'success' && 'Shops build succeeded' || 'Shops build failed' }}
          description: |
            **Branch:** ${{ github.ref_name }}
            ${{ github.event_name == 'pull_request' && format('**PR:** #{0}', github.event.pull_request.number) || '' }}

            ${{ job.status == 'success' && 'Build and tests completed successfully! ✅' || job.status == 'cancelled' && 'Build was cancelled. ⚠️' || 'Build or tests failed. ❌' }}
          color: ${{ job.status == 'success' && '5025616' || job.status == 'cancelled' && '16753920' || '15548997' }}
          url: ${{ format('https://github.com/{0}/actions/runs/{1}', github.repository, github.run_id) }}
          nodetail: true

  documentation-and-reporting:
    name: Documentation and Reports
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ !inputs.create_release_artifacts }}
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        id: checkout

      - name: Set up Java
        uses: actions/setup-java@v4
        id: setup-java
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: 'maven'

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        id: download-artifacts
        with:
          name: build-artifacts
          path: .

      - name: Check documentation and publish reports
        id: check-docs
        run: mvn validate site -DskipTests -Dmaven.main.skip -Dmaven.test.skip

      - name: Upload coverage reports to Codecov
        id: codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Check steps status
        id: check-status
        if: always()
        run: |
          if [ "${{ steps.checkout.outcome }}" == "success" ] && 
             [ "${{ steps.setup-java.outcome }}" == "success" ] && 
             [ "${{ steps.download-artifacts.outcome }}" == "success" ] && 
             [ "${{ steps.check-docs.outcome }}" == "success" ] && 
             [ "${{ steps.codecov.outcome }}" == "success" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

      - name: Send Discord documentation notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: ${{ steps.check-status.outputs.status == 'success' && 'Shops coverage reports updated' || 'Shops coverage report generation failed' }}
          description: |
            **Branch:** ${{ github.ref_name }}

            ${{ steps.check-status.outputs.status == 'success' && 'Test coverage reports have been updated for Shops! 📊' || job.status == 'cancelled' && 'Coverage report generation was cancelled. ⚠️' || 'Failed to generate coverage reports. ❌' }}
            ${{ steps.check-status.outputs.status == 'success' && format('View the latest coverage metrics for this branch: https://app.codecov.io/gh/BrendonButler/Shops/tree/{0}', github.ref_name) || '' }}
          color: ${{ steps.check-status.outputs.status == 'success' && '5814783' || job.status == 'cancelled' && '16753920' || '15548997' }}
          url: ${{ format('https://github.com/{0}/actions/runs/{1}', github.repository, github.run_id) }}
          nodetail: true
